package chain

const (
	BUCKET_BLOCK_HASH_PREFIX    = 0x01
	BUCKET_BLOCK_HEIGHT_PREFIX  = 0x02
	BUCKET_TRANSFER_HASH_PREFIX = 0x03
	BUCKET_UNSPENT_HASH_PREFIX  = 0x04
	BUCKET_UNSPENT_HAVE_PREFIX  = 0x05
	BUCKET_BALANCE_HASH_PREFIX  = 0x06
)
